CREATE SEQUENCE REALM_ID_SEQ START WITH 1;
CREATE SEQUENCE AUCTIONFILE_ID_SEQ START WITH 1;
CREATE TABLE REALM("ID" INTEGER NOT NULL PRIMARY KEY, "NAME" VARCHAR(30), "SLUG" VARCHAR(30), "REGION" VARCHAR(2), "STATUS" TINYINT(1));
CREATE TABLE REALMFOLDER("REALMID" INTEGER NOT NULL, "FOLDERTYPE" VARCHAR(10) NOT NULL, "PATH" VARCHAR(300) NOT NULL, PRIMARY KEY("REALMID", "FOLDERTYPE"), FOREIGN KEY("REALMID") REFERENCES REALM("ID"));
CREATE TABLE AUCTIONFILE("ID" INTEGER NOT NULL PRIMARY KEY, "REALM_ID" INTEGER NOT NULL, "URL" VARCHAR(100) NOT NULL, "LASTMODIFIED" NUMERIC(13) NOT NULL, "FILENAME" VARCHAR(30) NOT NULL, "FILESTATUS" VARCHAR(10) NOT NULL, FOREIGN KEY("REALM_ID") REFERENCES REALM("ID"));
