CREATE SEQUENCE REALM_ID_SEQ START WITH 1;
CREATE SEQUENCE AUCTIONFILE_ID_SEQ START WITH 1;
CREATE TABLE REALM("ID" INTEGER NOT NULL PRIMARY KEY, "NAME" VARCHAR(30), "SLUG" VARCHAR(30), "REGION" VARCHAR(2), "STATUS" TINYINT(1));
CREATE TABLE REALMFOLDER("REALMID" INTEGER not null, "FOLDERTYPE" VARCHAR(10) not null, "PATH" VARCHAR(300) not null, PRIMARY KEY("REALMID", "FOLDERTYPE"), FOREIGN KEY("REALMID") REFERENCES REALM("ID"));
CREATE TABLE AUCTIONFILE("ID" INTEGER NOT NULL PRIMARY KEY, "REALM_ID" INTEGER not null, "URL" VARCHAR(100), "LOADED" TINYINT(1), FOREIGN KEY("REALM_ID") REFERENCES REALM("ID"))
